rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'

urlpatterns = [
    path('about/', views.about, name='about'),
    path('', views.index, name='index'),
    path('category/<slug:category_name_slug>/',
        views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('register/', views.register, name='register'), 
    path('login/', views.user_login, name='login'),
    path('restricted/', views.restricted, name='restricted'),
    path('logout/', views.user_logout, name='logout'),
    path('like_category/', views.LikeCategoryView.as_view(), name='like_category'),
    path('suggest/', views.CategorySuggestionView.as_view(), name='suggest'),



]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'
    
    def __str__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)
    def __str__(self):
        return self.title

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from rango.models import Page, Category
from django.contrib.auth.models import User
from rango.models import UserProfile
# We could add these forms to views.py, but it makes sense to split them off into their own file.

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category',)
    
    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url
        
        return cleaned_data

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture',)

rango/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from rango.models import Category, Page, UserProfile
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm
from datetime import datetime
from django.views import View
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User


# Create your views here.

def index(request):
  #  return HttpResponse("Rango says hey there partner! (<a href='/rango/about/'>About</a>")
  category_list = Category.objects.order_by('-likes')[:5]
  context_dict = {}
  context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
  context_dict['categories'] = category_list
  page_list = Page.objects.order_by('-views')[:5]
  context_dict['pages'] = page_list

  visitor_cookie_handler(request)

  return render(request, 'rango/index.html', context=context_dict)



def about(request):
    context_dict = {}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    return render(request, 'rango/about.html', context=context_dict)

def show_category(request, category_name_slug):

  context_dict = {}
  try:

    category = Category.objects.get(slug=category_name_slug)

    pages = Page.objects.filter(category=category)
    context_dict['pages'] = pages

    context_dict['category'] = category
  except Category.DoesNotExist:

    context_dict['category'] = None
    context_dict['pages'] = None
  return render(request, 'rango/category.html', context=context_dict)

@login_required
def add_category(request):
  form = CategoryForm()
# A HTTP POST?
  if request.method == 'POST':
    form = CategoryForm(request.POST)
# Have we been provided with a valid form?
    if form.is_valid():
# Save the new category to the database.
        form.save(commit=True)
# Now that the category is saved, we could confirm this.
# For now, just redirect the user back to the index view.
        return redirect(reverse('rango:index'))
    else:
# The supplied form contained errors -
# just print them to the terminal.
      print(form.errors)
# Will handle the bad form, new form, or no form supplied cases.
# Render the form with error messages (if any).
  return render(request, 'rango/add_category.html', {'form': form})

@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except:
        category = None
    
    # You cannot add a page to a Category that does not exist... DM
    if category is None:
        return redirect(reverse('rango:index'))

    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)

        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()

                return redirect(reverse('rango:show_category', kwargs={'category_name_slug': category_name_slug}))
        else:
            print(form.errors)  # This could be better done; for the purposes of TwD, this is fine. DM.
    
    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context=context_dict)

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    
    return render(request, 'rango/register.html', context={'user_form': user_form, 'profile_form': profile_form, 'registered': registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('rango:index'))
            else:
                return HttpResponse("Your Rango account is disabled.")
        else:
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'rango/login.html')




class LikeCategoryView(View):
    @method_decorator(login_required)
    def get(self, request):
        category_id = request.GET['category_id']

        try:
            category = Category.objects.get(id=int(category_id))
        except Category.DoesNotExist:
            return HttpResponse(-1)
        except ValueError:
            return HttpResponse(-1)
        
        category.likes = category.likes + 1
        category.save()

        return HttpResponse(category.likes)

class CategorySuggestionView(View):
    def get(self, request):
        if 'suggestion' in request.GET:
            suggestion = request.GET['suggestion']
        else:
            suggestion = ''
        
        category_list = get_category_list(max_results=8, starts_with=suggestion)

        if len(category_list) == 0:
            category_list = Category.objects.order_by('-likes')

        
        return render(request, 'rango/categories.html', {'categories': category_list})

#@login_required
def restricted(request):
    return render(request, 'rango/restricted.html')

@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('rango:index'))

def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

def get_category_list(max_results=0, starts_with=''):
    category_list = []

    if starts_with:
        category_list = Category.objects.filter(name__istartswith=starts_with)
    
    if max_results > 0:
        if len(category_list) > max_results:
            category_list = category_list[:max_results]

    
    return category_list

def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie
    
    request.session['visits'] = visits

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    About Rango
{% endblock %}

{% block body_block %}
<!--h1>Rango says...</h1>
<div>
    here is the about page.<br />
    <strong>This tutorial has been put together by Ziyang Liu</strong><br/>
    <p>Visits: {{ visits }}</p>

</div>
<div>
<img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" /> <!-- New line -->
<!--img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of a Cat" /-->
<div class="container">
    <div class="col-md-6">
        <p>
            As the number of sites for learning a language increases, it becomes easier to organize these course names and 
site addresses together.On this basis, if the site to add the search language function, it is more convenient to manage the site address.In addition, the site's login and registration functions identify users and enable specific features to be 
presented to specific users.Finally, the site is able to perform permission checks on users who are not logged in. Without permission, users 
cannot perform certain operations
        </p>
        <p>Visits: {{ visits }}</p>
    </div>
    <div class="col-md-6">
        <div class="slider">
            <div class="callbacks_container">
                <ul class="rslides" id="slider">
                    <li><img src="{% static 'images/OIP.jfif' %}" class="img-responsive" alt=""/></li>
                    <li><img src="{% static 'images/R.jfif' %}" class="img-responsive" alt=""/></li>
                    <li><img src="{% static 'images/T.jfif' %}" class="img-responsive" alt=""/></li>      
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add a Category
{% endblock %}

{% block body_block %}
        <h1>Add a Category</h1>
        <div>
            <form id="category_form" method="post" action="{% url 'rango:add_category' %}">
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}
                    {{ field }}
                {% endfor %}
                <input type="submit" name="submit" value="Create Category" />
            </form>
        </div>
{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add a Page
{% endblock %}

{% block body_block %}
        <h1>Add a Page to {{ category.name }}</h1>
        <div>
            <form id="add_page_form" method="post" action="{% url 'rango:add_page' category.slug %}">
                {% csrf_token %}
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}
                    {{ field }}
                {% endfor %}
                <input type="submit" name="submit" value="Add Page" />
            </form>
        </div>
{% endblock %}

templates/rango/base.html
<!doctype html>
{% load staticfiles %}
{% load rango_template_tags %}

<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="https://cdn.jsdelivr.net/npm/@bootcss/v3.bootcss.com@1.0.10/favicon.ico">
    <link rel="canonical" href="https://getbootstrap.com/docs/3.4/examples/offcanvas/">
    <link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css' />
    <link href="{% static 'bootstrap/css/bootstrap.css' %}" rel='stylesheet' type='text/css' />
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Oxygen:300,400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'css/about.css' %}">
    <title>
        Rango - 
        {% block title_block %}
            How to Tango with Django!
        {% endblock %}
    </title>
    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/@bootcss/v3.bootcss.com@1.0.10/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="https://cdn.jsdelivr.net/npm/@bootcss/v3.bootcss.com@1.0.10/assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://cdn.jsdelivr.net/npm/@bootcss/v3.bootcss.com@1.0.10/examples/offcanvas/offcanvas.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="https://cdn.jsdelivr.net/npm/@bootcss/v3.bootcss.com@1.0.10/assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="https://cdn.jsdelivr.net/npm/@bootcss/v3.bootcss.com@1.0.10/assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <div>
        {% block body_block %}
        {% endblock %}
        </div>
       
        <hr />
    <nav class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Rango</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'rango:logout' %}">Logout</a></li>
                    <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
                {% else %}
                    <li><a href="{% url 'rango:register' %}">Sign Up</a></li>
                    <li><a href="{% url 'rango:login' %}">Login</a></li>
                {% endif %}
                    <li><a href="{% url 'rango:restricted' %}">Contact us</a></li>
                    <li><a href="{% url 'rango:about' %}">About</a></li>
                    <li><a href="{% url 'rango:index' %}">Index</a></li>
            </ul>
        </div><!-- /.nav-collapse -->
      </div><!-- /.container -->
    </nav><!-- /.navbar -->

   

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="https://cdn.jsdelivr.net/npm/@bootcss/v3.bootcss.com@1.0.10/assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://cdn.jsdelivr.net/npm/@bootcss/v3.bootcss.com@1.0.10/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="https://cdn.jsdelivr.net/npm/@bootcss/v3.bootcss.com@1.0.10/assets/js/ie10-viewport-bug-workaround.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@bootcss/v3.bootcss.com@1.0.10/examples/offcanvas/offcanvas.js"></script>

    <!--script src="{% static 'js/jquery-3.3.1.min.js' %}" crossorigin="anonymous"></script-->
    <script src="{% static 'js/rango-jquery.js' %}" crossorigin="anonymous"></script>
    <script src="{% static 'js/rango-ajax.js' %}" crossorigin="anonymous"></script>
    <script src="{% static 'bootstrap/js/responsiveslides.min.js' %}"></script>
    <script>
      $(function () {
        $("#slider").responsiveSlides({
          auto: true,
          nav: true,
          speed: 500,
          namespace: "callbacks",
          pager: true,
        });
      });
    </script>
    <script src="{% static 'bootstrap/js/jquery.easydropdown.js' %}"></script>
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
  </body>
</html>

templates/rango/categories.html
<ul>
    {% if categories %}
        {% for c in categories %}
            
            <a class="list-group-item" href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
        {% endfor %}
    {% else %}
        <li><strong>There are no categories present.</strong></li>
    {% endif %}
    </ul>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if category %}
    <h3 style="color:#fd926b">{{ category.name }}</h3>

    <div>
        <strong id="like_count">{{ category.likes }}</strong> likes
        {% if user.is_authenticated %}
        <button id="like_btn"
        data-categoryid="{{ category.id }}"
        class="btn btn-primary btn-sm"
        type="button">
        <span data-feather="thumbs-up"></span>
        Like Category
        </button>
        {% endif %}
        </div>
        
    {% if pages %}
    <ul class="menu">
        {% for page in pages %}
        <li class="item3"><a href="{{ page.url }}">{{ page.title }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <strong>No pages currently in category.</strong>
    {% endif %}

    {% if user.is_authenticated %}
    <a href="{% url 'rango:add_page' category.slug %}" class="btn1 btn-primary1">Add Page</a> <br />
    {% endif %}
    {% else %}
    The specified category does not exist.
    {% endif %}
{% endblock %}

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% load rango_template_tags %}

{% block title_block %}
Homepage
{% endblock %}

{% block body_block %}
<!-- <h1>Rango says...</h1>
         <div>
            {% if user.is_authenticated %}
                howdy {{ user.username }}!
            {% else %}
                hey there partner!
            {% endif %}
            <br />
            <strong>{{ boldmessage }}</strong><br />
        </div> -->

<style>
    .jumbotron img {
        width: 100%;
        height: auto;
    }
</style>


<div class="container">

    <div class="row row-offcanvas row-offcanvas-right">

        <div class="col-xs-12 col-sm-9">
            <p class="pull-right visible-xs">
                <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
            </p>
            <div class="jumbotron">
                <h2> {% if user.is_authenticated %}
                    Hi {{ user.username }}!
                    {% else %}
                    Hi visitor!
                    {% endif %}
                    <br /></h1>
                    <div class="slider">
                        <div class="callbacks_container">
                            <ul class="rslides" id="slider">
                                <li><img src="{% static 'images/OIP.jfif' %}" class="img-responsive" alt=""/></li>
                                <li><img src="{% static 'images/R.jfif' %}" class="img-responsive" alt=""/></li>
                                <li><img src="{% static 'images/T.jfif' %}" class="img-responsive" alt=""/></li>      
                            </ul>
                        </div>
                    </div>
            </div>
            <div class="row">
                <div class="col-xs-6 col-lg-4">
                    <h2>Most Liked Categories</h2>
                    {% if categories %}
                    <div class="nav1">
                        <ul>
                            {% for category in categories %}
                            <li><a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a></li>
                            {% endfor %}
                        </ul>
                        {% else %}
                        <strong>There are no categories present.</strong>
                        {% endif %}
                    </div>
                </div>
                <!--/.col-xs-6.col-lg-4-->
                <div class="col-xs-6 col-lg-4">
                    <h2>Most Viewed Pages</h2>
                    {% if pages %}
                    <div class="nav1">
                        <ul>
                            {% for page in pages %}
                            <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                            {% endfor %}
                        </ul>
                        {% else %}
                        <strong>There are no pages present.</strong>
                        {% endif %}
                    </div>
                </div>


                <!--/.col-xs-6.col-lg-4-->
            </div>
            <!--/row-->
        </div>
        <!--/.col-xs-12.col-sm-9-->

        <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar">
            <!-- <div class="list-group">
                <a href="#" class="list-group-item active">Link</a>
                <a href="#" class="list-group-item">Link</a>
                <a href="#" class="list-group-item">Link</a>
                <a href="#" class="list-group-item">Link</a>
                <a href="#" class="list-group-item">Link</a>
                <a href="#" class="list-group-item">Link</a>
                <a href="#" class="list-group-item">Link</a>
                <a href="#" class="list-group-item">Link</a>
                <a href="#" class="list-group-item">Link</a>
                <a href="#" class="list-group-item">Link</a>
            </div> -->
            <div class="w-75 ml-3">
                <input type="search"
                id="search-input"
                class="form-control ds-input"
                placeholder="Search..." />
                </div>
                
            <!-- <div class="list-group" id="categories-listing">
                {% if categories %}
                {% for c in categories %}
                <a href="{% url 'rango:show_category' c.slug %}" class="list-group-item">{{ c.name }}</a>
                {% endfor %}

                {% endif %} 
            </div> -->
            <div class="sidebar-sticky" id="categories-listing">
                {% block sidebar_block %}
                {% get_category_list category %}
                {% endblock %}
                </div>
                

        </div>
        <!--/.sidebar-offcanvas-->
    </div>
    <!--/row-->

    <hr>

    <footer>
        <p>&copy; 2021 Company, Inc.</p>
    </footer>

</div>
<!--/.container-->


{% endblock %}

templates/rango/login.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
    <head>
		<meta charset="utf-8" />
		<title>Sign in</title>
		<link rel="stylesheet" href="{% static 'css/login.css' %}">
        <link rel="stylesheet" href="{% static 'css/iconfont.css' %}">
	</head>
    <body>
        <div id="login-box">
            <h1>Login to Rango</h1>
            <div class="input-box">
                <form id="login_form" method="post" action="{% url 'rango:login' %}">
                    {% csrf_token %}
                    <div class="input-box">
                        <i class="iconfont">&#xe609;</i>
                        
                        <input type="text" name="username" placeholder="UserName" />
                    </div>
                    <div class="input-box">
                        <i class="iconfont">&#xe605;</i>
                        <input type="password"  name="password" placeholder="UserPassword" />
                    </div>
                    <button>Sign in</button>
                </form>
            </div>
        </div>
    </body>
</html>

templates/rango/register.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
    <head>
		<meta charset="utf-8" />
		<title>Sign in</title>
		<link rel="stylesheet" href="{% static 'css/register.css' %}">
        <link rel="stylesheet" href="{% static 'css/iconfont.css' %}">
	</head>
    <body>
        {% if registered %}
        Rango says: <strong>thank you for registering!</strong>
        <a href="{% url 'rango:index' %}">Return to the homepage.</a><br />
        {% else %}
        Rango says: <strong>register here!</strong><br />
        <div id="login-box">
            <h1>Register</h1>
            <div class="input-box">
                <form id="login_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <font color="white">
                    {{ user_form.as_p }}
                    {{ profile_form.as_p }}
                    <button>Register</button>
                </form>
            </div>
        </div>
        {% endif %}
    </body>
</html>

templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load staticfiles%}

{% block title_block %}
    Restricted Page
{% endblock %}

{% block body_block %}
<div class="container">
    <div class="col-md-6">
        <h3 style="color:#fd926b">Call Us</h3>
        <p>Call us on 99999999999 to discuss your requirements.</p>
        <h3 style="color:#fd926b">Email Us</h3>
        <p>Enail us on wqhgfewoihf@12e</p>
        <h3 style="color:#fd926b">Find Us</h3>
        <p>You can find us at the following address:
        </br>
            Chuan Ltd</br>
            345-349 TTR Street</br>
            Glasgow</br>
            G40 3HW</p>
    </div>
    <div class="col-md-6">
        <div id="googleMap" style="width:500px;height:500px;"></div>
    </div>
    <script>
      function initialize()
      {
        var mapProp = {
          center: new google.maps.LatLng(51.508742,-0.120850),
          zoom:7,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById("googleMap"),mapProp);
      }
      
      function loadScript()
      {
        var script = document.createElement("script");
        script.type = "text/javascript";
        script.src = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBxZdV7BY_PXXhWL6QGp2XAWcX8VrgXsFc&sensor=false&callback=initialize";
        document.body.appendChild(script);
      }
       window.onload = loadScript;
    </script>
</div>
{% endblock %}